pragma solidity ^0.8.0;

import "ensdomains/ens-contracts/contracts/registry/ENS.sol";
import "ensdomains/ens-contracts/contracts/registry/ENSRegistry.sol";
import "openzeppelin/contracts/access/Ownable.sol";
import "openzeppelin/contracts/token/ERC721/ERC721.sol";
import "openzeppelin/contracts/token/ERC721/IERC721.sol";
import "openzeppelin/contracts/token/ERC721/IERC721Receiver.sol";
import "openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol";
import "openzeppelin/contracts/utils/Address.sol";
import "openzeppelin/contracts/utils/Context.sol";
import "openzeppelin/contracts/utils/Strings.sol";
import "openzeppelin/contracts/utils/introspection/ERC165.sol";
import "openzeppelin/contracts/utils/introspection/IERC165.sol";
import "src/BulkRegister.sol";
import "src/root/Controllable.sol";
import "src/root/Root.sol";
import "src/universal/IUniversalRegistrar.sol";
import "src/universal/RegistrarAccess.sol";
import "src/universal/UniversalRegistrar.sol";
